// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaayagiwircvwvhcxivc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphYXlhZ2l3aXJjdnd2aGN4aXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NjM1NTYsImV4cCI6MjA1NzIzOTU1Nn0.nY8gq2GsSaTfOVWsyYi14PIhm1OENq8Z84J1o6B-fOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);